#import "../libs/template.typ": *

= Koszul Complexes

@weibel[Section 4.5].

#definition[
Let $R$ be a ring and let $x in Z lr((R))$ be a central element. Then we
define the *Koszul complex* $K lr((x))$ of $x$ to be the chain complex
$ 0 arrow.r R arrow.r^x R arrow.r 0 $ concentrated in degrees $1$ and $0$.

We denote the generator of $K lr((x))_1$ by $e_x$, so that
$K lr((x))_1 eq R dot.op e_x comma K lr((x))_0 eq R dot.op 1$, and
$d (e_x) eq x$.

If $bd(x) = (x_1, ..., x_n)$ is a finite sequence of central elements, define 
$
  K(bd(x)) = K(x_1) tpr K(x_2) tpr ... tpr K(x_n)
$
]
#definition[
For an $R$-module $A$, we define the *Koszul homology* and *Koszul
cohomology* to be
$ H_q lr((bd(x) comma A)) & eq H_q lr((K lr((bd(x))) times.circle_R A)) comma\
H^q lr((bd(x) comma A)) & eq H^q lr(("Hom"_R lr((K lr((bd(x))) comma A)))) dot.basic $
]

#example[
 As an example,
$K lr((x comma y))$ is the complex
#align(center,image("../imgs/2023-11-25-10-34-10.png",width:80%))
]

#TODO what is exterior product

#proposition[
  $K_p (bd(x))$ is a free module with rank $vec(n, p)$.
]
#proof[
  By induction.
]

The degree $p$ part of $K lr((bd(x)))$ is a free $R$-module generated by the
symbols
$ e_(i_1) and dots.h.c and e_(i_p) eq 1 times.circle dots.h.c times.circle 1 times.circle e_(x_(i_1)) times.circle dots.h.c times.circle e_(x_(i_p)) times.circle dots.h.c times.circle 1 quad lr((1 <= i_1 lt dots.h.c lt i_p <= n)) dot.basic $

(There are in total $n$ terms of the tensor product and in the degree $p$ part of $K(bd(x))$ there should be $p$ terms that come from the degree $1$ part of $K(x_j)$ and thus are $e_x_(j)$, and the remaining ($n-p$) terms should come from the degree $0$ part and are $1$.) 

In particular, $K_p lr((bd(x)))$ is isomorphic to the $p$-th exterior
product $Lambda^p R^n$ of $R^n$ and has rank $vec(n, p)$, so $K lr((x))$
is often called the *exterior algebra complex*. 

The derivative
$K_p lr((bold(bd(x)))) arrow.r K_(p minus 1) lr((bold(x)))$ sends
$e_(i_1) and dots.h.c and e_(i_p)$ to
$sum lr((minus 1))^(k plus 1) x_(i_k) e_(i_1) and dots.h.c and$
$hat(e)_(i_k) and dots.h.c and e_(i_p)$.


#proposition[
$lr({H_q lr((x comma minus))})$ is a
homological $delta$-functor, and that
$lr({H^q lr((bold(x) comma minus))})$ is a cohomological $delta$-functor
with
$ H_0 lr((bold(x) comma A)) eq A slash lr((x_1 comma dots.h.c comma x_n)) A\
H^0 lr((bold(x) comma A)) eq "Hom"lr((R slash x R comma A)) eq lr({a in A colon x_i a eq 0 upright(" for all ") i}) dot.basic $
]
<koszul-zero>

#proposition[
  There are isomorphisms
$H_p lr((x comma A)) tilde.equiv H^(n minus p) lr((x comma A))$ for all
$p$. 
]

#lemma("Künneth Formula for Koszul Complexes")[
If
$C eq C_ast$ is a chain complex of $R$-modules and $x in R$, there
are exact sequences
$ 0 arrow.r H_0 lr((x comma H_q lr((C)))) arrow.r H_q lr((K lr((x)) times.circle_R C)) arrow.r H_1 lr((x comma H_(q minus 1) lr((C)))) arrow.r 0 $
]
<kunneth-koszul>

#proof[
  $K(x) tpr C$ by definition is a direct sum of two complexes and thus we can write a #sest of complexes: 
  $
    ses(C, K(x) tpr C, C[-1])
  $
  which is associated to the long exact sequence: 
  $
    H_(q plus 1) lr((C lr([minus 1]))) arrow.r^diff H_q lr((C)) arrow.r H_q lr((K lr((x)) times.circle C)) arrow.r H_q lr((C lr([minus 1]))) arrow.r^diff H_q lr((C)) 
  $
  where $H_(q+1) (C[-1]) = H_q (C)$ and $H_(q) (C[-1]) = H_(q-1) (C)$. One can find that the connecting homomorphism $diff$ is multiplication by $x$. Now we have 
  $
    H_q lr((C)) arrow.r^x H_q lr((C)) arrow.r H_q lr((K lr((x)) times.circle C)) arrow.r H_(q-1) lr((C))  arrow.r^x H_(q-1) lr((C)) 
  $
  which leads to the #sest 
  $
    ses(coker(H_q (C) ->^x H_q (C)), H_q lr((K lr((x)) times.circle C)), ker(H_(q-1) (C) ->^x H_(q-1) (C)))
  $
  

  Now since $ H_q (C) ->^x H_q (C) = (R ->^x R) tpr H_q (C) $

  We find 
  $
    coker(H_q (C) ->^x H_q (C)) = H_0 (x, H_q (C))
  $ and 
  $
    ker(H_q (C) ->^x H_q (C)) = H_1 (x, H_(q) (C))
  $
  and the result follows.
]

#definition[
  If $A$ is an $R$-module, a *regular sequence* on $A$ is a sequence of elements $(x_1, ..., x_n)$ where each $x_i in R$ such that $x_1$ is a non-zero-divisor on $A$ and each $x_i$ is a non-zero-divisor on $A over (x_1, ..., x_(i-1))$.
]

#corollary[
  If $bd(x) = (x_1, ... , x_n)$ is a regular sequence on an $R$-module $A$, then $H_q (bd(x), A) = 0$ for $q != 0$ and $H_0 (bd(x), A) = A over (x_1, ..., x_n) A$. 
]

#proof[
  We already know $H_0(bd(x), A)$ from @koszul-zero. We prove the $q != 0$ part by induction. If $x$ is a non-zero-divisor on $A$ then $K(x) tpr A$ is 
  $
    0 -> A ->^x A -> 0
  $
  so $H_1 = ker x = 0$ and $H_0 = A over x A$. 

  Let $x  = x_n$ and $bd(y) = (x_1, ..., x_(n-1))$. By @kunneth-koszul, we have a #sest 
  
  $
    ses(H_0(x, H_q (bd(y), A)), H_q (bd(x), A), H_1 (x, H_(q-1) (bd(y), A)))
  $
  For $q >= 2$, the flanking terms are both $0$ by induction and hence $H_q (bd(x), A) = 0$. 
  
  For $q  = 1$, we get 
  $
    H_1 (bd(x), A) iso H_1 (x, H_(0) (bd(y), A)) = H_1 (K(x) tpr H_(0) (bd(y), A))
  $
  Since
  $
    H_(0) (bd(y), A) = A over (x_1, ..., x_(n-1)) A
  $ we see that $K(x) tpr H_(0) (bd(y), A)$ is the complex 
  $
    A over (x_1, ..., x_(n-1)) A ->^x A over (x_1, ..., x_(n-1)) A
  $
  which has kernel zero because $x$ is a non-zero-divisor of $A over (x_1, ..., x_(n-1)) A$, and thus has $H_1 = 0$. 
]

#corollary[
  If $bd(x) = (x_1, ..., x_n)$ is a regular sequence on $R$, then $K(bd(x))$ is a free resolution of $R over I$, where $I  =(x_1, ..., x_n) R$, and 
  $
    H_p (bd(x), A) = Tor_p^R (R over I, A) \
    H^p (bd(x), A) = Ext_p^R (R over I, A) \
  $
]
#remark[
  #TODO Tower, Past paper, Serre...
]

// Suppose that $upright(x) eq lr((x_1 comma dots.h comma x_n))$ is a
// finite sequence of central elements in $R$. Then $K lr((upright(x)))$ is
// the chain complex
// $ K lr((x_1)) times.circle_R dots.h times.circle_R K lr((x_n)) dot.basic $



// Koszul resolution

// Let $x in R$ be a central element. Let $K(x)$ be the chain complex 
// $
//   0->R->^x R ->0
// $ 
// in degrees $0,1$. We call the generator in degree $1$ $e_x$ so $d(e_x) = x$. 

