name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ
      - name: Rename color PDF file
        run: |
          mv main.pdf hom-alg-notes-color.pdf
      - name: Replace color scheme in template
        run: |
          sed -i '0,/color.typ/s//bw.typ/' libs/template.typ
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ
      - name: Rename BW PDF file
        run: |
          mv main.pdf hom-alg-notes-bw.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: |
            hom-alg-notes-color.pdf
            hom-alg-notes-bw.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} - ${{ env.DATE }}"
          files: "*.pdf"
